### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by msrober** [Badging-System/Application-layer#45]
I think there should be a change to the Schema. The current issue I am having is trying to fetch every user data after fetching a team. For instance, every time we hit the teams endpoint we will have to hit the database for every member and coach id. This create a ton of overhead on the front end or back-end wherever the logic is done. I cant finish my task until this is resolved. 

`{"_id":{"$oid":"5e4c2f2f0a4d2855acfb42cd"},
"Name":"Team1","Coach":{"$oid":"5e4c2f340a4d2855acfb42d5"},"Admin":{"$oid":"5e4c2f340a4d2855acfb42d4"},"Badges":[],"Members":{"0":{"$oid":"5e4c2f300a4d2855acfb42ce"},"1":{"$oid":"5e4c2f300a4d2855acfb42cf"},"2":{"$oid":"5e4c2f300a4d2855acfb42d0"},"3":{"$oid":"5e4c2f300a4d2855acfb42d1"},"4":{"$oid":"5e4c2f300a4d2855acfb42d2"},"5":{"$oid":"5e4c2f300a4d2855acfb42d3"}}}`

**Comment by msrober** [comment]
Karl what do you think? @karl-cardenas-coding

**Comment by dmaitha** [comment]
Here is a start to what you're looking for.   I can work help out more later.  You need to get the count of the members array and project out the coach name.  Google how to do projections with mongoose .populate. ALSO!!! You need to add a ref tag to the Coach in the team schema for this to work.  It references users.

function query() {
  mongoDB.mongooseConnect();
  Team.find({}, { Name: 1, _id: 0 })
    .populate("Coach")
    .populate("Members")
    .exec((err, results) => {
      if (err) {
        console.log(err);
      } else {
        mongoDB.mongoogeDisconnect();
        console.log(results);
      }
    });
}
OUTPUT:====================================
[ { Members:
     [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    Name: 'Team1',
    Coach:
     { Teams: [],
       _id: 5e4b5a48464661862aa61612,
       Username: 'coachDave',
       First_name: 'David',
       Last_name: 'Coach',
       Role: 'Coach',
       Active: true,
       Email: 'badgingCoach@gmail.com' } } ]

**Comment by karl-cardenas-coding** [comment]
Is the question where the logic should be handled for the team endpoint? I would defer to the backend to handle gathering all the users for a team vs making the UI make multiple calls.  

You guys might already be doing this but look into secondary indexes, that's a great way to optimize queries. This would be a good fit for a secondary index.
